### ISSUE TITLE
overzealous jsbeautification of a closing "}])"?

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/javascript-style-guide#14]
based on @ScottDowne's work in wmo, it looks like this:
```javascript
  .directive('a', [
    '$location',
    '$anchorScroll',
    '$route',
    function ($location, $anchorScroll, $route) {
      return {
        ...
      };
    }])
```
is getting rewritten to 
```javascript
  .directive('a', [
    '$location',
    '$anchorScroll',
    '$route',
    function ($location, $anchorScroll, $route) {
      return {
        ...
      };
    }
])
```

This might be a little too much cleanup?

**Comment by ScottDowne** [comment]
I'll confirm that this wasn't a change I made because of jscs, but either way, issue still stands.

**Comment by ScottDowne** [comment]
So, this was in fact jsbeautify, and taking a closer look, I agree with it.

Having a block start and end at the same indentation makes sense.

**Comment by gvn** [comment]
No longer using jsbeautifier.
