### ISSUE TITLE
Deprecate JSBeautify

### ISSUE THREAD

**Issue by gvn** [MozillaFoundation/javascript-style-guide#19]
Once this issue is resolved we should be able to get rid of JSBeautify...

https://github.com/jscs-dev/node-jscs/issues/516

**Comment by hzoo** [comment]
JSCS added the --autofix option as of 1.12 on most of the whitespace rules, so the issue is partially resolved (enough to be able to begin using it for those kinds of rules).

**Comment by gvn** [comment]
@simonwex Maybe we should just go ahead and remove it now?
