### ISSUE TITLE
Proposal: Migrate to ESLint

### ISSUE THREAD

**Issue by gvn** [MozillaFoundation/javascript-style-guide#22]
I think migrating to [ESLint](http://eslint.org/) may make sense (at least for our React projects). We're moving over to it for Webmaker because JSXHint is deprecated.

Pros:
- Can do linting *and* style checking
- Pluggable rules
- ES6 / React / JSX support
- "If you are using both JSHint and JSCS on your files, then using just ESLint will be faster."

Cons:
- No auto formatting from what I can tell. It looks like this did land in JSCS, but I haven't tried it. (EDIT: It can do *some* autoformatting...I'd expect more to come)

**Comment by Pomax** [comment]
:+1:
