### ISSUE TITLE
ES6 does not seem covered yet

### ISSUE THREAD

**Issue by Pomax** [MozillaFoundation/javascript-style-guide#3]
It totally should be

**Comment by ashleygwilliams** [comment]
i'd like to re awaken this conversation, see https://github.com/mozilla/publish.webmaker.org/pull/35

**Comment by simonwex** [comment]
It's time. Relevant: https://github.com/airbnb/javascript/issues/247

**Comment by gvn** [comment]
Resolved by ESLint
