### ISSUE TITLE
Maybe enable strict mode

### ISSUE THREAD

**Issue by gideonthomas** [MozillaFoundation/javascript-style-guide#32]
Node does not allow block-scoped declarations (like `let`) unless strict mode is enabled. Is there a reason why strict mode is disabled / is there a way to get around this for node?

**Comment by gvn** [comment]
Hah! I just ran into this today as well. There's a PR up now...sorry for the inconvenience! :+1:

**Comment by gvn** [comment]
If you're in a rush you can override the rule in your package.json or as an option to the CLI, but I expect we'll get this merged soon.

**Comment by gvn** [comment]
Ok, grab `v2.2.0` and you should be all set!

**Comment by gideonthomas** [comment]
cool thanks @gvn!

**Comment by Pomax** [comment]
reopening this for a moment: the current version of node says it supports `let` by default,

**Comment by Pomax** [comment]
the following code, using node 5.4, works as expected with `let` and a local strict declaration:
```
"use strict";

function test() {
  var x = Math.random(),
      y = Math.random();
  if (x < y) {
    let r1 = "yes";
    console.log(r1);
  } else {
    let r1 = "no";
    console.log(r1);
  }
  console.log(typeof r1);
}

test();
```

**Comment by gvn** [comment]
If you have a file `test.js` containing:

```javascript
let foo = 1;
```

And run `node test.js` you get the following error:

```
(function (exports, require, module, __filename, __dirname) { let foo = 1;
                                                              ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

If you update `test.js` to the following no errors are thrown:

```javascript
"use strict";

let foo = 1;
```

This is with node `5.5.0`.

**Comment by Pomax** [comment]
wait, why would you use `let` in global scope? It's the block-scoping variable declaration, you'd still use `var` if you need function or global scoping?

**Comment by gvn** [comment]
I guess there's no great reason to do it.

Regardless, do you think it'd be a bad thing to have 1 global `"use strict";` pragma? I'm fine removing it again if let works in block scope in node without it.

**Comment by Pomax** [comment]
I guess it depends on what you mean with "one" - you can't issue "use strict" in node and have it apply outside of that one file, so for offline/server-side JS each file will have to declare it; I'd be quite okay with that, but then I do like strict mode because it makes you write saner code. As long as we don't advocate `--use-strict` for node to "get around needing to type *use strict* all the time", though, because that'd be pretty horrible.

**Comment by gvn** [comment]
Agreed on never using flags to run Node (at least never `--use-strict`).

By "1 global" I mean each file requiring one "use strict" at the top (aka: leave things as-is). What I don't like is function scoped "use strict" as it feels excessively noisy.

**Comment by Pomax** [comment]
yup, then we're on the same page.

**Comment by gvn** [comment]
Yep, and just to be extra clear we are currently requiring one "use strict" pragma at the top of each JS file. 

So, as is, we *do* want strict. :cake:

**Comment by Pomax** [comment]
:100:
