### ISSUE TITLE
Sass Migration – RFC

### ISSUE THREAD

**Issue by gvn** [MozillaFoundation/javascript-style-guide#36]
We have a general consensus on moving away from LESS to standardizing on Sass as a CSS preprocessor.

However, we need to decide which of the 2 syntaxes to use: **Sass or SCSS**.

*This ticket is a request for comments on the migration and more specifically which syntax should be our standard.*

Relevant articles:
- [Sass's indented syntax has not been and will never be deprecated!](http://www.thesassway.com/news/sass-is-here-to-stay)
- [Sass vs. SCSS: which syntax is better?](http://www.thesassway.com/editorial/sass-vs-scss-which-syntax-is-better)

**Tabulation:**

SASS: 1.5 (Yeah, I gave half a vote...that's right.)
SCSS: 3

**Comment by gvn** [comment]
Personally, I like the terseness and meaningful indentation of SASS syntax. However there is a stronger community preference for SCSS, and it is a little more friendly for beginners and general CSS migration.

Linting is also very important and will be defined based on a standard RC similar to our ESLint one. There are a few linters for Sass:

[sass-lint](https://github.com/sasstools/sass-lint)

- Lints SASS & SCSS.
- Node-based.
- Seems buggy from my experience, but still generally usable and has reasonable velocity.

[scss-lint](https://github.com/brigade/scss-lint/)

- *Only* lints SCSS.
- Ruby based.
- I haven't given it a whirl yet, but if stars are any indication then it's heavily used.

I think anyone who does any CSS work in the Foundation should weigh in if they have thoughts:

@simonwex @alanmoo @alicoding @mmmavis @ScottDowne @vazquez @flukeout @Pomax 

Please @ mention anyone I forgot!

**Comment by alanmoo** [comment]
I have a very strong preference for SCSS syntax, as it's simply a superset of vanilla CSS. Related to your CSS migration point: when you need to copy and paste styles from the browser, it's much easier.

I'm a bit curious as to how much longer we'll even need preprocessors at all, as CSS is evolving to meet many of their uses, but that's probably a future conversation.

@gvn Keep me in the loop regarding linting rules and such, I'm...highly opinionated...in this area.

**Comment by vazquez** [comment]
I have enjoyed writing Sass in the past. The rigour that Sass dictates due to its whitespace delineation keeps the CSS in better shape than SCSS in my opinion (ie. nesting)

With that being said, SCSS works just fine. Perhaps keeping our linting rules strict as to the levels of nesting would solve the problem.

**Comment by gvn** [comment]
Yeah, I think linting rules will serve us very well and also reduce the effective differences between the syntaxes quite a bit. We can (and should) enforce indentation via linting rules for example.

To me the choice boils down to a few things:

- Personal formatting preference (I don't like semis and curlies, but that's a *preference*)
- Tooling (There are more options with SCSS)
- Community (Vast majority is using SCSS)

Given that linting solves most of my grievances with SCSS I'm fine using it. I'm more curious how everyone else feels regarding the two syntaxes...

**Comment by flukeout** [comment]
My vote goes to SCSS - I think it's closer to what I'm already used to (LESS) and I'm not a huge fan of indentation being meaningful in any way other than to help make things more readable.

Related to linting - can we please have a very easy way to lint our style sheets on our local machines while working on them?

**Comment by gvn** [comment]
Linting is a bit tangential and I'd like to get into a more in depth separate conversation about it once we pick a syntax.

However, I'll say that most editors can read an RC file and give you automatic feedback (or feedback on save, which I prefer). Also, we should make sure projects have a linting task in `package.json` and that it's tied into Travis.

Anyway, let's try to resolve the syntax choice first. Then we can get into the weeds with linting. :wink:

**Comment by Pomax** [comment]
my vote goes out to SCSS, since I'm also not a fan of semantic whitespace.

**Comment by simonwex** [comment]
This looks settled: SCSS + sass-lint (Node linter) 

If sass-lint proves to be too buggy and doesn't meet our needs for rule enforcement, we can use the Ruby project, until it is ready. I'd really rather not ask our Windows contributors to install Ruby on their systems just to lint SCSS, though.

**Comment by gvn** [comment]
Sounds good. :+1:

**Comment by gvn** [comment]
Looks like `sass-lint` is actually working significantly better with the SCSS format, so that's a win.
